name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/setup-node-modules.yml

  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Lint
        run: npm run lint

      - name: type check
        run: npm run type-check

      - name: knip unused
        run: npm run knip

      # 計測結果を表示する
      - uses: Kesin11/actions-timeline@v1
