name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Run-Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: "^v18.19.0"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: type check
        run: npm run type-check

      - name: knip unused
        run: npm run knip

      # 計測結果を表示する
      - uses: Kesin11/actions-timeline@v1
