name: Agent-Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write

jobs:
  Run-PR-Agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Please use Japanese."
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "Please use Japanese."
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "Please use Japanese."
