name: Agent Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  run-pr-agent:
    runs-on: ubuntu-latest
    name: Run Agent Review
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: review-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
          # PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Please use Japanese."
          # PR_REVIEWER.EXTRA_INSTRUCTIONS: "Please use Japanese."
          # PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "Please use Japanese."
