name: Setup Node Modules

on:
  workflow_call:
    outputs:
      node-version:
        description: "The Node.js version used"
        value: ${{ jobs.setup.outputs.node-version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node.outputs.node-version }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        id: node
        with:
          cache: npm
          node-version: "^v18.19.0"

      - uses: actions/cache@v4
        id: cache
        with:
          path: app/node_modules
          key: |
            ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.node.outputs.node-version }}-npm-${{ hashFiles('app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: app
