name: Build-Storybook

on:
  pull_request:
    paths: [src/**, .storybook/**, package.json, package-lock.json, mocks/**]
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Run-Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: "^v18"

      - name: npm install, build, and test
        run: npm i

      - name: storybook build
        run: npm run storybook:build
