name: Build-Storybook

on:
  pull_request:
    paths: [src/**, .storybook/**, package.json, package-lock.json, mocks/**]
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/shared/setup-node-modules.yml

  Run-Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: storybook build
        run: npm run storybook:build

      # 計測結果を表示する
      - uses: Kesin11/actions-timeline@v1
