name: UT

on:
  pull_request:
    paths: [src/**, package.json, package-lock.json, mocks/**]
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Run-Unit-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/setup-node-modules

      - name: Unit test
        run: npm run test

      # 計測結果を表示する
      - uses: Kesin11/actions-timeline@v1
